// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7xrM9lhg0hmHnMgqgndG3lHnkTVHsDrQ',
    appId: '1:765013274908:web:f42119d13a7c601509cad9',
    messagingSenderId: '765013274908',
    projectId: 'matchquizapp-1a8b3',
    authDomain: 'matchquizapp-1a8b3.firebaseapp.com',
    storageBucket: 'matchquizapp-1a8b3.firebasestorage.app',
  );

  // NOTE: Android/iOS/macOS/Windows dùng chung projectId.
  // Nếu cần chạy trên platform khác, cần đăng ký app riêng trên Firebase Console.
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7xrM9lhg0hmHnMgqgndG3lHnkTVHsDrQ',
    appId: '1:765013274908:web:f42119d13a7c601509cad9',
    messagingSenderId: '765013274908',
    projectId: 'matchquizapp-1a8b3',
    storageBucket: 'matchquizapp-1a8b3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7xrM9lhg0hmHnMgqgndG3lHnkTVHsDrQ',
    appId: '1:765013274908:web:f42119d13a7c601509cad9',
    messagingSenderId: '765013274908',
    projectId: 'matchquizapp-1a8b3',
    storageBucket: 'matchquizapp-1a8b3.firebasestorage.app',
    iosBundleId: 'com.example.matchquizapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7xrM9lhg0hmHnMgqgndG3lHnkTVHsDrQ',
    appId: '1:765013274908:web:f42119d13a7c601509cad9',
    messagingSenderId: '765013274908',
    projectId: 'matchquizapp-1a8b3',
    storageBucket: 'matchquizapp-1a8b3.firebasestorage.app',
    iosBundleId: 'com.example.matchquizapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7xrM9lhg0hmHnMgqgndG3lHnkTVHsDrQ',
    appId: '1:765013274908:web:f42119d13a7c601509cad9',
    messagingSenderId: '765013274908',
    projectId: 'matchquizapp-1a8b3',
    authDomain: 'matchquizapp-1a8b3.firebaseapp.com',
    storageBucket: 'matchquizapp-1a8b3.firebasestorage.app',
  );
}
