// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYh0WI58_b_MXHoU47xEDQxlBjPOwh4O8',
    appId: '1:562848665768:web:1bd748a4e6aff63289b29d',
    messagingSenderId: '562848665768',
    projectId: 'doanmoi-911d1',
    authDomain: 'doanmoi-911d1.firebaseapp.com',
    databaseURL: 'https://doanmoi-911d1-default-rtdb.firebaseio.com',
    storageBucket: 'doanmoi-911d1.firebasestorage.app',
    measurementId: 'G-CTGJXJ2YDX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSU7eryDUZFMWiUq4gjkLsr7QgB2N-NGU',
    appId: '1:562848665768:android:17d00a909d2e91ce89b29d',
    messagingSenderId: '562848665768',
    projectId: 'doanmoi-911d1',
    databaseURL: 'https://doanmoi-911d1-default-rtdb.firebaseio.com',
    storageBucket: 'doanmoi-911d1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNpOGcvxnejuZ_iL-9eV89iC3L0gUh2fo',
    appId: '1:562848665768:ios:68566df9aa62084789b29d',
    messagingSenderId: '562848665768',
    projectId: 'doanmoi-911d1',
    databaseURL: 'https://doanmoi-911d1-default-rtdb.firebaseio.com',
    storageBucket: 'doanmoi-911d1.firebasestorage.app',
    iosBundleId: 'com.example.matchquizapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNpOGcvxnejuZ_iL-9eV89iC3L0gUh2fo',
    appId: '1:562848665768:ios:68566df9aa62084789b29d',
    messagingSenderId: '562848665768',
    projectId: 'doanmoi-911d1',
    databaseURL: 'https://doanmoi-911d1-default-rtdb.firebaseio.com',
    storageBucket: 'doanmoi-911d1.firebasestorage.app',
    iosBundleId: 'com.example.matchquizapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYh0WI58_b_MXHoU47xEDQxlBjPOwh4O8',
    appId: '1:562848665768:web:108a829fb9c9410c89b29d',
    messagingSenderId: '562848665768',
    projectId: 'doanmoi-911d1',
    authDomain: 'doanmoi-911d1.firebaseapp.com',
    databaseURL: 'https://doanmoi-911d1-default-rtdb.firebaseio.com',
    storageBucket: 'doanmoi-911d1.firebasestorage.app',
    measurementId: 'G-5ZF5S8C3YY',
  );
}
